COMMON_PATH:=${abspath ${dir ${lastword ${MAKEFILE_LIST}}}}

export PYTHONPATH:=$(COMMON_PATH)/../..
WORKSHOPROOT=${COMMON_PATH}/../../../../../..
include $(shell cocotb-config --makefiles)/Makefile.sim

#$(info *** Base path :  ${COMMON_PATH} )
