VERILOG_SOURCES += ../common/timescaleit.v Counter.v
TOPLEVEL=Counter
MODULE=CounterTester

include $(shell cocotb-config --makefiles)/Makefile.inc
include $(shell cocotb-config --makefiles)/Makefile.sim
