VERILOG_SOURCES += ../common/timescaleit.v StreamFifo.v
TOPLEVEL=StreamFifo
MODULE=StreamFifoTester

include $(shell cocotb-config --makefiles)/Makefile.inc
include $(shell cocotb-config --makefiles)/Makefile.sim
